### ISSUE TITLE
Implementing Matter in new environments example

### ISSUE THREAD

**Issue by Orzech99** [project-chip/matter.js#1001]
## Overview
Hello!  I am currently working on integrating the core Matter.js functionality into a React Native application. From my understanding, there are several platform-specific parts that need to be implemented on my own. These are:

- BigInt/UInt8Array
- Network
- Crypto
- Storage
- Time
- BLE 
- Wi-Fi/Thread Commissioning

## Questions
1. Is my understanding correct that I need to implement these functionalities to get Matter.js working in a React Native environment?
2. Could you provide guidance or examples on where and how to implement these interfaces?

## Additional Context
I have successfully used matter-node.js in a Node.js environment and am now transitioning to React Native. Any advice or pointers to relevant documentation would be greatly appreciated.

## Future Contribution
After managing to get this to work, I plan to share my solution with the community. My side goal is to make the Matter protocol and Matter.js more accessible to a wider range of developers, especially those working with React Native.

**Thank you for your help!**

**Comment by Apollon77** [comment]
@Orzech99 Did you saw https://github.com/project-chip/matter.js/tree/main/packages/matter.js-react-native ?! We currently already work on react native and should be near to done ... The PR https://github.com/project-chip/matter.js/pull/988 is the current next/last step for next testing round.

So if you are familiar with react native please have a look at the package and code (there also your questions should be answered) also on the PR and provide Feedback if you see anything strange or broken.

With this last PR we "should" be fine because anything should be integrated ... reality tests will then show where ewe really stand. If you like to join these experiments and support in finalization you're welcome :-)

I hope you did not do too much work already, but if then maybe a good idea to compare :-)
