### ISSUE TITLE
Errors after pairing with google home

### ISSUE THREAD

**Issue by elausys** [project-chip/matter.js#1257]
Hi,

We have a bridge device that we can successfuly pair and control from Apple home.
When repeating the same process with google home, the pairing process is shown completed successfully in Google Home and the bridged devices appear in the app but no connection is established to the devices.

We have the following errors in the log :

```
[2m2024-10-04 08:56:48.942 ERROR  [0;1;90mExchangeManager      [0;31mCannot find a session for ID 40345
[2m2024-10-04 08:56:56.836 ERROR  [0;1;90mSubscriptionHandler  [0;31mError sending subscription update message (error count=1): RetransmissionLimitReachedError
[2m2024-10-04 08:57:58.661 ERROR  [0;1;90mExchangeManager      [0;31mThe previous message has not been acked yet, cannot send a new message.
[2m2024-10-04 09:00:02.270 ERROR  [0;1;90mSubscriptionHandler  [0;31mSending update failed 3 times in a row, canceling subscription 2540059429 and let controller subscribe again.
```

Attached the complete error log file of the server.
[server-error.log](https://github.com/user-attachments/files/17254705/server-error.log)

Google home is on latest version and successfully controlling other matter devices.

What could be the issue ?

 Thank you in advance !

**Comment by elausys** [comment]
We also have this error after repeating the pairing with apple home : 

1|server   | 2024-10-04 10:07:46.887 ERROR  CaseServer           An error occurred during the commissioning Fabric cannot be found from destinationId

Although devices can still be controlled from apple home.

**Comment by Apollon77** [comment]
Ok I think we need to analyze this in steps ;-)

First of all "Cannot find a session for ID 40345" can always happen directly after a device restart when the controller still thinks the old sessions are still existing (but they are removed on restart). Usually a controller tries to establish a new session after some of these tries.
So this error most likely related to a restart and not to a commisioning process.

So ideally set the loglevel to debug and try this again.

For commissioning: If you use Google Home on iOS then you currently need to register the device as test device in the Google console else Google commissioning fails. No idea why they added this limitation to iOS now after lifting it on Android some time ago. See https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#google-home-ecosystem

So with Debug log I think I can have a deeper look what exactly happens

**Comment by elausys** [comment]
Hi Apollon77,

Thank you for your answer.
When testing pairing on Google Home, it is done using a Android tablet, not from IOS.

I tried to repeat pairing but it did not suceed this time.
See attached the full logs.
[server-error.log](https://github.com/user-attachments/files/17310999/server-error.log)
[server-out.log](https://github.com/user-attachments/files/17311000/server-out.log)

Thanks a lot.

Best Regards,

**Comment by Apollon77** [comment]
Ok ... first of all ... please tell me what I see in the log?

I see a running subscription 135936054 which is running "all the time" ... then I see a new device being initialized on port 5540 and announced.

If I should guess then it would be that you startup multiple devices and use the same port 5540 ? (I can not verify because I do not see details for that running subscription).
But if this is the case then honestly this can not work because then you mix up stuff.

So you either need to correctly stop and kill the running device before starting new OR make sure that you only have one device listening to the same port number, else exactly such things happen as you describe.

On the other side the commisioning process in the log stopped at "csrRequest" which is commonly the case when google verifies that the vendor/product Id matches to the things setup in the dev console and this does not match. So then I would repeat the question again if you read the above mentioned docs and did this registration? Maybe it then magically works? ;-)

**Comment by Apollon77** [comment]
Great to hear. I still do not understand in which cases Google requires this registration and when not :-(

**Comment by Apollon77** [comment]
Ok log show the following. There seems to be an active fabric 1 already. What's this? Because it was not covered by the logs? The admin subject used for commissioning is the same as for the following commissioning which is ok when it is google app and hub ... but as said ... questions because seems incomplete log.
Also what is 2a02:a03f:aafb:6600:a5e8:41fe:e772:2989 ? Just to know the context

The log then shows commissioning of a second fabric #2 and all is fine until addNoc. Then also the reconnection to the operational device happens but then instead of sending "commissioningComplete" message it does some read requests to gather details about the device.
This read started 11:11:02.433 and needed till 11:11:09.408 to collect the data ... that's 7 seconds?! What you use as device or as storage here? Seems very slow ... normally these are "milliseconds" ...

Interestingly also no resubmissions of the read message came in during this timeframe - which should have been the case anyway irrelevant ... or was your system somehow at 100% and so nothing else happened? because all resubmissions of the original read message came in after we sent the first DataReport starting 11:11:09.425 and then with 10ms delays which normally are longer backoffs.
So it seems that something completely blocked your system including incoming MDNS while the data were collected for the read.

So in the end it was a read timeout for google and thats why it was stuck there.

Se yes we have planned to optimize reads to send out data already while collecting them ... but in fact no idea if this would have helped that much because your system really seemed to were blocked a lot by whatever ... Sooooo ... whats up there -  that would be your homework *gg* ;-)

**Comment by Apollon77** [comment]
PS: If you like ... join the Discord I created for Matter Integrators ... there we can also chat more directly then here via Github issues
