### ISSUE TITLE
color-control: Color mode defaults to xy even when not supported

### ISSUE THREAD

**Issue by kennylevinsen** [project-chip/matter.js#1468]
The default value of the `colorMode` attribute is `ColorControl.ColorMode.CurrentXAndCurrentY`.

When a command comes in to change the color, such as `moveToHueAndSaturation`, `setColorMode` will attempt to convert the current color from XY to HSV, but `currentX`/`currentY` is undefined at that point, and in the case of home-assistant-matter-hub, `Xy` is not even enabled. The color conversion ends up yielding `NaN`, and all state management breaks.

See:
- https://github.com/t0bst4r/home-assistant-matter-hub/issues/225
- https://github.com/t0bst4r/home-assistant-matter-hub/blob/1b717ac561e04bbff6aef40880404a6eeda4b125/packages/backend/src/matter/behaviors/color-control-server.ts

I imagine that the fix would be either:
1. Ensure that `colorMode` is never initialized to a value that does not match the supported and initialized color modes
2. Ensure that `currentX`/`currentY` (and all the other `current*` values) is always initialized so that all transitions just yield default values.

Doing `this.state.colorMode = ColorControl.ColorMode.ColorTemperatureMireds;` within home-assistant-matter-hub's `ColorControlServerBase.initialize` fixes things, but that seems like a workaround rather than a fix.

**Comment by Apollon77** [comment]
In fact this is a good topic, but nothing matter,js can currently take care of.

The default "1" which means XY is the default for the ColorMode field. That it does not make sense if XY is not supported is clear but currently the specs tells it that way. In fact ColorMode is a mandatory attribute anyway, so it should not have any default at all and should be needed to be set by the developer. I can change it to be exactly like this, but also this requires a change in the using library like you try in your PR (maybe there is a better place).

So yes I will remove the default because it makes no sense and will report this spec issue, but the change you do is still needed!
