### ISSUE TITLE
Running two devices at the same time result in clones

### ISSUE THREAD

**Issue by FezVrasta** [project-chip/matter.js#296]
I'm running the two OnOffLightDevice with different unique IDs, but for some reason when I pair them to Apple Home I see they act as one, switching one, the other reflects the status.

Any idea of why this is happening?

Is `productId` supposed to be unique as well maybe?

**Comment by Apollon77** [comment]
Please verify that you sue different storage areas! if you use the CLI scripts then you need to specify "-store myname" to define a storage directory - at leaset on the second one. Else it uses the same storage and so "is" onyl one device.

Might that be the reason? Wlse please provide more details on how you start/operate it or your code and debug logs

**Comment by FezVrasta** [comment]
Thanks for the answer. I'm using two different storage locations.

I'm running the example script twice basically. Is that the intended way to run two devices or should I run a single Matter server and add multiple devices to it?

**Comment by FezVrasta** [comment]
If I set different passcodes it generates different pairing codes but then I can't pair the devices to Apple Home anymore.

**Comment by FezVrasta** [comment]
It looks like the port number needs to be different for each device? Is there a way to use the same port for all my devices?

**Comment by FezVrasta** [comment]
So, different port and discriminator seems to be the right combination, it works for a bit but then the second device becomes unresponsive. I'm very confused.

**Comment by Apollon77** [comment]
Ok yes the port number needs to be different when you start multiple processes in parallel. else only the frst one is "reactive" - but in fact you should have seen this in the debug logs when trying to pair :-)
Different discriminator helps if you put both devices in parallel as "uncommissioned" into the network because then apple might only try one. And with different port and different discriminator also different passcodes should work.

To your other question: If you use multiple processes then each is scanning for all mdns messages which is a bit overhead. So you can use one MatterServer and put miltiple CommissioningServer nodes in there - then MDNS is used centralized. With 2 processes this is fine also using them ... the more you need the bigger this overhead gets.

But good to have this. I will ad this to the readme too.

**Comment by stefano055415** [comment]
> I don't have a direct solution, but have you looked at the Bridge and MultiDevice examples? - Both are designed to allow handling of multiple matter devices in the same nodejs process although last time I tried, Alexa didn't support MultiDevice, - bridges were fine.

@JimBuzbee 

I also noticed that Alexa no longer supports endpoints, if I commission a device with 2 endpoints on Alexa I only see the first one.

That there is some documentation that says this, it seems strange to me that Amazon hasn't implemented this yet

**Comment by Apollon77** [comment]
Yes Compose devices are not yet supported by Amazonn as it seems. But bridges are working since some weeks

**Comment by stefano055415** [comment]
Yes, I had noticed that the bridges had started to work.

Let's hope they introduce this implementation soon too

For the project I'm trying to do I would prefer to use a multidevice
