### ISSUE TITLE
Why moving away from TypeScript project references?

### ISSUE THREAD

**Issue by vilic** [project-chip/matter.js#376]
Having been playing with Matter.js for some days and the building process during debugging is really painful. And I noticed it was once configured with project references but was removed in [this commit](https://github.com/project-chip/matter.js/commit/6c7676fe6c60796595d5b566d809299524b4e84e) (at least for `matter-node.js` package).

What is the reason not using project references, especially considering better incremental building & editor experience?

**Comment by lauckhart** [comment]
Good question, looks like removing the references was inadvertent when we cleaned up the tsconfig files.  We should be able to add them back...  Send PR if you'd like or I'll take a look at it when I get a moment.

**Comment by vilic** [comment]
Would love to send a PR but there would probably be something to do between tsconfigs and the current building process (esbuild). I would like to know how open to this you guys are, and what’s your bottom line. 😆

**Comment by lauckhart** [comment]
We're open minded, especially if it improves dev experience. 🙂  Ping here or in Discord if you want a quick gut check.

**Comment by Apollon77** [comment]
Ookkk. Seems I missed that removal in the reviews but yes this let me understand some experiences I had in the last time when it came to cross project things. So yes let's please re-add them ;-)

@vilic a PR would be cool ... else I would do it once I finish my current topic. PR would be faster I think ;-)

**Comment by lauckhart** [comment]
Thanks @vilic this makes sense.

Some of what you're seeing are intentional decisions because tsc is so slow.  We have src/ and test/ with a single tsconfig so we can run typechecking on both simultaneously.  The theoretical downsides haven't been an issue in practice...  But as we decompose the more monolithic packages and optimize types maybe build times will become less painful. 

Likewise we use one pass to generate type declarations for ESM and CommonJS to minimize tsc invocation.  The emitted declarations were identical in either mode.  It might not be too bad if we were to run tsc no-emit in CJS mode...  Do you have a reference for what kind of issue this might expose?  There are definitely constraints on how CommonJS dependencies are imported but esbuild and/or node throw errors there so we catch them without tsc.

Separating the testing globals from tools/ makes sense.  All of the packages technically do have dependencies on tools/ because they use the tooling "bin" scripts but the logical separation would be nice.

We did discuss dropping CommonJS but didn't feel like it was quite time yet.  The non-library projects should only build in one format, if you're seeing otherwise it's a bug.  I think we used CommonJS for the node apps but IIRC that was just to limit the number of changes when we swapped the build system.

**Comment by vilic** [comment]
> Some of what you're seeing are intentional decisions because tsc is so slow.

Actually I don't fully get this, with `--watch` option, the incremental build should be fast enough (< 1s, I think). But for the current building setup, I found it not straightforward (if it is doable) to watch & build incrementally. A clean build would only take less than 10s, which is totally acceptable to me as usually that happens only a few times in a day.

Considering we only need to build ESM during development most of the time, and anyway we build the declaration files, I don't see practical benefits separating that into two.

> We have src/ and test/ with a single tsconfig so we can run typechecking on both simultaneously.

I think that could easily been down by adding an intermediate tsconfig with only references (and Ctrl/Cmd+Shift+B search watch and select that tsconfig and profit). Actually I already have done this at the first day playing with the project structure.

> Likewise we use one pass to generate type declarations for ESM and CommonJS to minimize tsc invocation...

Yeah no one likes redundancy, especially comes to build optimization. The problem building against one format should be manageable & negligible, what I have encountered trying to setting up the project references is something related to `import.meta` (but as you said, it generates runtime error anyway). I've seen suggestions from the TS team member recommending compiling them against different formats, but too bad I cannot find that post again.

> All of the packages technically do have dependencies on tools/ because they use the tooling "bin" scripts but the logical separation would be nice.

That can already be done by referencing tools in `devDependencies`, but not for TypeScript project references.

I'll try to get the project references setup up pushed to my own fork tomorrow, and let's see where it goes. 😃

**Comment by lauckhart** [comment]
Cool, I don't think there's anything that'll preclude you from setting up project references and using `tsc --watch` but if you run into something LMK, hopefully a quick fix.

Don't discount clean build times entirely, when jumping branches regularly and/or iterating on a PR they happen a lot.  When working on code gen it may as well not be an incremental build. 🙄

**Comment by vilic** [comment]
Haha, that might be a tolerance issue: 30s build type would still be within my comfort zone, if the CI is completed within 1 min I would call that very fast. ;)

Then I'll only push the tsconfig.json files and related changes for `--watch`, was trying to figure out a proper way for dual formats build.
