### ISSUE TITLE
Energy measurement device missing && subscription generic problems

### ISSUE THREAD

**Issue by antonio-gabriele** [project-chip/matter.js#539]
Dear,
I'm dealing with these issues:
1) No energy measurement device. So I cannot verify power consumption (Cluster 0B04 + Modbus energy meter)
2) I have some composed devices that have OnOff + Energy Measurement or TemperatureMeasurement + RelativeHumidityMeasurement. How can I implement them?
3) Subscription work excellent on Temperature + Relative Humidity, but update on OnOff Cluster (Lights + Outlets) are slow and work exclusively via Read Attribute!!! What did I miss?
4) I want to give code contribution to project. I'm implementing a Matter/Modbus-KNX-Zigbee bridge + project scaffolding.

**Comment by Apollon77** [comment]
Hey,

please use discussions or join the discord for discussion related or how-to topics. We want to use the GitHub issues for real "issues".

1.) Check matter specification ... there is NO such cluster as of Matter 1.2 ... so stay tuned for Matter 1.3 ... so all "as designed"
2.) Composed devices see composed device example. In matter.js you create an commissioningServer and use addDevice to add an OnOffDevice, an Tem,peratureSensorDevice and a HumidityDevice to it. this will give you an composed devcie. Only Apple and Google support that right now!
3.) Please provide a log for this. I use this all over the place in testing and all works smooth also for many other devs (else we would had complains already). So we can check your code/implementation.
4.) Any support is highly appreciated ... check the GitHub project for the current topics on the todo list or bring your ideas as feature Requests (discussion sections) or via Discord. Please do not start on anything regarding devices because Greg is currently finalizing the full device type support - we will soon have clases for all matter 1.1 device types in all combinations with an updated high level API on the devices.

**Comment by lauckhart** [comment]
@antonio-gabriele code contributions would be great!  I plan to create a branch later today with the new code.  Still a WIP but you can see where we're headed and hopefully it helps to align plans.
