### ISSUE TITLE
Wrong Temperaturemeasurement attribute definition

### ISSUE THREAD

**Issue by antonio-gabriele** [project-chip/matter.js#553]
Hi,
in TemperatureMeasurementCluster.ts I get:
`
            minMeasuredValue: Attribute(0x1, TlvNullable(TlvInt16.bound({ min: -27315 })), { default: 32768 }),
`
but for an INT16 the maximum number is 32767 (as correct definition Number.ts)
This break my work because I initialize all attributes with default value and I get schema error violation.
`
      throw new import_MatterError.ValidationError(`Invalid value: ${value} is above the maximum, ${this.max}.`);
`

**Comment by JimBuzbee** [comment]
If this is an issue, it also appears in ElectricalMeasurementCluster.ts where TlvInt16 values have a default of 32768

I wonder if instead of using numeric values we should generate something like TlvInt16.INT16_MAX? 

But thinking out loud, I recall that the standard doesn't always define default values as min or max...

**Comment by Apollon77** [comment]
This these were errornous input data for the generation process ... actiually the chip tool XMLs were wrong because they contained this errornous value.
... and it is containiung this still :-)

https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/temperature-measurement-cluster.xml#L28C9-L28C9

default is higher then max ... hehe ...

I created https://github.com/project-chip/connectedhomeip/issues/30775 to inform the workgroup guys and I will prepare a generation fix for it for matter.js

@JimBuzbee The ElectricalMesaurementCluster is kind of not existing ... there was a XML in the chip repo as we generated last time, so it is added - but was removed and is not in 1.1 and not in 1.2, so I would igmore this for now. But thx for noticing!

**Comment by Apollon77** [comment]
@antonio-gabriele is a new nightly version sufficient with the fix or do you prefer a 0.7.2?

**Comment by JimBuzbee** [comment]
Re: ElectricalMesaurementCluster  - I wondered about that - Went to double-check in the standard and didn't find it :-)

**Comment by Apollon77** [comment]
Ok I had the feeling something is wrong with the last changes ... here is why ... https://github.com/project-chip/matter.js/pull/556

I think this makes more sense

**Comment by antonio-gabriele** [comment]
I will wait for 0.7.2. Many thanks.

**Comment by Apollon77** [comment]
0.7.2 is out
