### ISSUE TITLE
Window Covering Cluster issue on the persist of attributes TargetPositionLiftPercent100ths and TargetPositionTiltPercent100ths

### ISSUE THREAD

**Issue by Luligu** [project-chip/matter.js#724]
Hi,
I noticed that these two attributes are not persist = true in the cluster definition.
They should be persist = true like the two current positions.
The Home app always go in an undetermined status on restart because CurrentPositionLiftPercentage and CurrentPositionTiltPercentage are persisted and so current can be different from target till we set both to the same value.
Thanks.

**Comment by Apollon77** [comment]
In fact they can not be persisted in my eyes because if the device somehow is turned off while a movement is done and such and start up with this value being different then "current" then the startup would need to "solve" this situation and mopve to target positivion. This is not really intended.

I would more see the logic that "target" could be set to the current value in the cluster initialization logic. The it is made sure they are in sync

WDYT?

**Comment by Luligu** [comment]
I agree with this.
The problem is that the cluster restore happens when you call matterServer.start() after the initialization is done. 
But it is possible to do a second initialization after matter server has started.
What do you think?
The specifics mark both target and current persist I guess.

**Comment by Apollon77** [comment]
In fact you need to have a command implementation anyway because matter.js do not have (yet) a default implememtation, right? So you have a cluster commnd implementation? And with this you can also write code for "Initialize" of the cluster ... just do it there

**Comment by Apollon77** [comment]
Fixed by #844 default implementation ins new API flow
