### ISSUE TITLE
Spec scraping issue with "powered numbers" like 2^62

### ISSUE THREAD

**Issue by Luligu** [project-chip/matter.js#950]
Example: Little bug in MeasurementAccuracyRange.ts generated file

Where:
rangeMin: TlvField(0, TlvInt64.bound({ min: -262, max: 262 })),
and 
rangeMax: TlvField(1, TlvInt64.bound({ min: -262, max: 262 })),

should be something like this  in my opinion:

rangeMin: TlvField(0, TlvInt64.bound({ min: -(2 ** 62), max: 2 ** 62 })),
and 
rangeMax: TlvField(1, TlvInt64.bound({ min: -(2 ** 62), max: 2 ** 62 })),

**Comment by Apollon77** [comment]
@lauckhart seems like a spec scraping error because also the spec.ts contains these numbers
![Bildschirmfoto 2024-06-12 um 08 28 38](https://github.com/project-chip/matter.js/assets/11976694/22cdfaa7-3298-4af7-9eed-f0ab240f9144)

Before I just add an override maybe you have a chance to have a look at scraping and we fix "correctly". Thank you

**Comment by lauckhart** [comment]
Superscripts are pretty fiddly to extract but if 2^62 is a common constant worst case I can probably special case it. Will take a look tomorrow.
